import type { JsonObject, JsonValue } from '../json.js';

interface BaseOptions {
  providerKey: string;
  clientOptions?: Readonly<Record<string, unknown>>;
  providerOptions?: Readonly<JsonObject>;
}

/**
 * What every file request carries.
 *
 * No `model`, unlike every other capability: a file is not generated by one and
 * the endpoints take none. Carrying the field anyway would invite a caller to
 * set it and expect it to matter.
 */
abstract class FileRequestBase {
  readonly #providerKey: string;

  readonly #clientOptions: Readonly<Record<string, unknown>>;

  readonly #providerOptions: JsonObject;

  constructor(options: BaseOptions) {
    this.#providerKey = options.providerKey;
    this.#clientOptions = options.clientOptions ?? {};
    this.#providerOptions = { ...(options.providerOptions ?? {}) };
  }

  providerKey(): string {
    return this.#providerKey;
  }

  clientOptions(): Readonly<Record<string, unknown>> {
    return this.#clientOptions;
  }

  providerOptions(): JsonObject;
  providerOptions(path: string): JsonValue | undefined;
  providerOptions(path?: string): JsonObject | JsonValue | undefined {
    return path === undefined ? this.#providerOptions : this.#providerOptions[path];
  }
}

export interface UploadFileRequestOptions extends BaseOptions {
  filename: string;
  content: Uint8Array;
  mimeType?: string | null;
}

export class UploadFileRequest extends FileRequestBase {
  readonly filename: string;

  /**
   * BYTES, where the reference takes a PHP string.
   *
   * A PHP string is a byte array; a JavaScript one is UTF-16 text, and passing
   * a PDF through it corrupts the file silently. The types diverge because the
   * languages do.
   */
  readonly content: Uint8Array;

  readonly mimeType: string | null;

  constructor(options: UploadFileRequestOptions) {
    super(options);
    this.filename = options.filename;
    this.content = options.content;
    this.mimeType = options.mimeType ?? null;
  }
}

export interface ListFilesRequestOptions extends BaseOptions {
  limit?: number | null;
  afterId?: string | null;
  beforeId?: string | null;
}

export class ListFilesRequest extends FileRequestBase {
  readonly limit: number | null;

  readonly afterId: string | null;

  /**
   * Carried, and NOT sent to OpenAI, because OpenAI's files endpoint has no
   * `before` parameter — only `after`. Kept on the request because the
   * reference has it and a provider that paginates both ways can read it;
   * dropping it silently in the mapper is where it belongs, not here.
   */
  readonly beforeId: string | null;

  constructor(options: ListFilesRequestOptions) {
    super(options);
    this.limit = options.limit ?? null;
    this.afterId = options.afterId ?? null;
    this.beforeId = options.beforeId ?? null;
  }
}

export interface FileIdRequestOptions extends BaseOptions {
  fileId: string;
}

/**
 * The three requests that are nothing but an id.
 *
 * One class behind three names rather than three identical ones — they differ
 * in which method takes them, not in what they hold.
 */
class FileIdRequest extends FileRequestBase {
  readonly fileId: string;

  constructor(options: FileIdRequestOptions) {
    super(options);
    this.fileId = options.fileId;
  }
}

export class GetFileMetadataRequest extends FileIdRequest {}

export class DeleteFileRequest extends FileIdRequest {}

export class DownloadFileRequest extends FileIdRequest {}
